class AddColumnToPricingPages < ActiveRecord::Migration
  def change
    add_column(:pricing_pages, :tender_limit1, :text)
    add_column(:pricing_pages, :tender_limit1_1, :text)
    add_column(:pricing_pages, :tender_limit1_2, :text)
    add_column(:pricing_pages, :tender_limit1_3, :text)
    add_column(:pricing_pages, :tender_limit1_4, :text)
    add_column(:pricing_pages, :tender_limit1_5, :text)
    add_column(:pricing_pages, :tender_limit1_6, :text)
    add_column(:pricing_pages, :tender_limit1_7, :text)
    add_column(:pricing_pages, :tender_limit1_8, :text)
    add_column(:pricing_pages, :tender_limit1_9, :text)
    add_column(:pricing_pages, :tender_limit1_0, :text)
    add_column(:pricing_pages, :tender_limit1_11, :text)
    add_column(:pricing_pages, :tender_limit1_12, :text)
    add_column(:pricing_pages, :tender_limit1_13, :text)

    add_column(:pricing_pages, :tender_limit2_1, :text)
    add_column(:pricing_pages, :tender_limit2_2, :text)
    add_column(:pricing_pages, :tender_limit2_3, :text)
    add_column(:pricing_pages, :tender_limit2_4, :text)
    add_column(:pricing_pages, :tender_limit2_5, :text)
    add_column(:pricing_pages, :tender_limit2_6, :text)
    add_column(:pricing_pages, :tender_limit2_7, :text)
    add_column(:pricing_pages, :tender_limit2_8, :text)
    add_column(:pricing_pages, :tender_limit2_9, :text)
    add_column(:pricing_pages, :tender_limit2_0, :text)
    add_column(:pricing_pages, :tender_limit2_11, :text)
    add_column(:pricing_pages, :tender_limit2_12, :text)
    add_column(:pricing_pages, :tender_limit2_13, :text)
    add_column(:pricing_pages, :tender_limit2_14, :text)

    add_column(:pricing_pages, :tender_limit3_1, :text)
    add_column(:pricing_pages, :tender_limit3_2, :text)
    add_column(:pricing_pages, :tender_limit3_3, :text)
    add_column(:pricing_pages, :tender_limit3_4, :text)
    add_column(:pricing_pages, :tender_limit3_5, :text)
    add_column(:pricing_pages, :tender_limit3_6, :text)
    add_column(:pricing_pages, :tender_limit3_7, :text)
    add_column(:pricing_pages, :tender_limit3_8, :text)
    add_column(:pricing_pages, :tender_limit3_9, :text)
    add_column(:pricing_pages, :tender_limit3_0, :text)
    add_column(:pricing_pages, :tender_limit3_11, :text)
    add_column(:pricing_pages, :tender_limit3_12, :text)
    add_column(:pricing_pages, :tender_limit3_13, :text)
    add_column(:pricing_pages, :tender_limit3_14, :text)


  end
end
