require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CompanyPagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CompanyPage. As you add validations to CompanyPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompanyPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all company_pages as @company_pages" do
      company_page = CompanyPage.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:company_pages)).to eq([company_page])
    end
  end

  describe "GET #show" do
    it "assigns the requested company_page as @company_page" do
      company_page = CompanyPage.create! valid_attributes
      get :show, params: {id: company_page.to_param}, session: valid_session
      expect(assigns(:company_page)).to eq(company_page)
    end
  end

  describe "GET #new" do
    it "assigns a new company_page as @company_page" do
      get :new, params: {}, session: valid_session
      expect(assigns(:company_page)).to be_a_new(CompanyPage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested company_page as @company_page" do
      company_page = CompanyPage.create! valid_attributes
      get :edit, params: {id: company_page.to_param}, session: valid_session
      expect(assigns(:company_page)).to eq(company_page)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CompanyPage" do
        expect {
          post :create, params: {company_page: valid_attributes}, session: valid_session
        }.to change(CompanyPage, :count).by(1)
      end

      it "assigns a newly created company_page as @company_page" do
        post :create, params: {company_page: valid_attributes}, session: valid_session
        expect(assigns(:company_page)).to be_a(CompanyPage)
        expect(assigns(:company_page)).to be_persisted
      end

      it "redirects to the created company_page" do
        post :create, params: {company_page: valid_attributes}, session: valid_session
        expect(response).to redirect_to(CompanyPage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved company_page as @company_page" do
        post :create, params: {company_page: invalid_attributes}, session: valid_session
        expect(assigns(:company_page)).to be_a_new(CompanyPage)
      end

      it "re-renders the 'new' template" do
        post :create, params: {company_page: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested company_page" do
        company_page = CompanyPage.create! valid_attributes
        put :update, params: {id: company_page.to_param, company_page: new_attributes}, session: valid_session
        company_page.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested company_page as @company_page" do
        company_page = CompanyPage.create! valid_attributes
        put :update, params: {id: company_page.to_param, company_page: valid_attributes}, session: valid_session
        expect(assigns(:company_page)).to eq(company_page)
      end

      it "redirects to the company_page" do
        company_page = CompanyPage.create! valid_attributes
        put :update, params: {id: company_page.to_param, company_page: valid_attributes}, session: valid_session
        expect(response).to redirect_to(company_page)
      end
    end

    context "with invalid params" do
      it "assigns the company_page as @company_page" do
        company_page = CompanyPage.create! valid_attributes
        put :update, params: {id: company_page.to_param, company_page: invalid_attributes}, session: valid_session
        expect(assigns(:company_page)).to eq(company_page)
      end

      it "re-renders the 'edit' template" do
        company_page = CompanyPage.create! valid_attributes
        put :update, params: {id: company_page.to_param, company_page: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested company_page" do
      company_page = CompanyPage.create! valid_attributes
      expect {
        delete :destroy, params: {id: company_page.to_param}, session: valid_session
      }.to change(CompanyPage, :count).by(-1)
    end

    it "redirects to the company_pages list" do
      company_page = CompanyPage.create! valid_attributes
      delete :destroy, params: {id: company_page.to_param}, session: valid_session
      expect(response).to redirect_to(company_pages_url)
    end
  end

end
